import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import QueryProviders from "./QueryProvider";
import ModalProvider from "./ModalProvider";
import { MSWProvider } from "./MSWProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const notoSans = Noto_Sans_KR({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VeriBadge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={notoSans.className}>
      <body className={`${geistSans.variable} overflow-y-auto antialiased`}>
        <QueryProviders>
          <MSWProvider>{children}</MSWProvider>
        </QueryProviders>
        <ModalProvider />
      </body>
    </html>
  );
}
